services:

  myapp:
    image: seedsync/stage/deb
    container_name: seedsync_stage_deb
    build:
      context: ../../../..
      dockerfile: src/docker/stage/deb/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ${SEEDSYNC_DEB}
        target: /install/seedsync.deb
        read_only: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8800/server/status"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 10s
