services:

  myapp:
    image: seedsync/stage/deb
    container_name: seedsync_stage_deb
    build:
      context: ../../../..
      dockerfile: src/docker/stage/deb/Dockerfile
    tty: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ${SEEDSYNC_DEB}
        target: /install/seedsync.deb
        read_only: true

      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
