services:

  myapp:
    image: seedsync/stage/deb
    container_name: seedsync_stage_deb
    build:
      context: ../../../..
      dockerfile: src/docker/stage/deb/Dockerfile
    tty: true
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
      - /sys/fs/cgroup
    volumes:
      - type: bind
        source: ${SEEDSYNC_DEB}
        target: /install/seedsync.deb
        read_only: true
