site_name: SeedSync
theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: teal
    accent: teal
    font: false
  logo: images/logo.png
  favicon: images/favicon.png
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
site_url: https://thejuran.github.io/seedsync
repo_name: thejuran/seedsync
repo_url: https://github.com/thejuran/seedsync
nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - FAQ: faq.md
